#!/usr/bin/env python
# -*- coding: utf-8 -*-
# https://github.com/shenwei356/bio_scripts
# Author     : Wei Shen
# Contact    : shenwei356@gmail.com
# LastUpdate : 2015-10-04

from __future__ import print_function

import argparse
import csv
import re
import sys


def csv_reader(fh, delimiter, quotechar):
    reader = csv.reader(fh, delimiter=delimiter, quotechar=quotechar)
    once = True
    for row in reader:
        yield row
    return


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="csv2tab",
        epilog="https://github.com/shenwei356/bio_scripts")

    parser.add_argument('csvfile',
                        nargs='*',
                        type=argparse.FileType('r'),
                        default=sys.stdin,
                        help='csvfile')

    parser.add_argument("-f",
                        type=str,
                        default=",",
                        help='field separator [,]')
    parser.add_argument("-q", type=str, default='"', help='quote char["]')

    args = parser.parse_args()

    writer = csv.writer(sys.stdout,
                        delimiter='\t',
                        quotechar=args.q,
                        quoting=csv.QUOTE_MINIMAL)

    stdinflag = False

    # If "iter(sys.stdin.readline, '')" in the flowing for-loop, first line
    # of stdin will be missing
    if args.csvfile is sys.stdin:
        stdinflag = True
        args.csvfile = [iter(sys.stdin.readline, '')]

    for f in args.csvfile:
        if not stdinflag:
            f = iter(f.readline, '')

        next_row = csv_reader(f, args.f, args.q)
        for row in next_row:
            writer.writerow(row)
