#!/usr/bin/env perl
# https://github.com/shenwei356/bio_scripts

use strict;
use Getopt::Long;

my $usage = <<USAGE;

unique - just like the basic function of uniq, 
         but no need of sorting, so it's FASTER!

Usage: unique [options] [files]
Options:
   -n, --show-count  Print count in the beginning of line
   -h, --help        Show this help

Of cause, this script could read data from STDIN.
And outputs are in random order.

https://github.com/shenwei356/bio_scripts
USAGE

my $args = {};
GetOptions(
    'help|h'       => \$$args{help},
    'show-count|n' => \$$args{show_count},
) or die $usage;

die $usage if $$args{help};

my %map = ();
while (<>) {
    chomp;
    $map{$_} += 1;
}

if ( $$args{show_count} ) {
    print "$map{$_}\t$_\n" for keys %map;
}
else {
    print "$_\n" for keys %map;
}

