#!/usr/bin/env perl
# https://github.com/shenwei356/bio_scripts
#
# tab2fasta - transfrom column table to fasta fromat
#
# This script is usually used in pair with fasta2tab.
#

use strict;
use BioUtil::Seq;

# get the file list
my @files = ();
for my $file (@ARGV) {
    for my $f ( glob $file ) {
        push @files, $f;
    }
}
if ( @files == 0 ) {
    push @files, 'STDIN';
}

for my $file (@files) {
    my $fh = undef;

    if ( $file eq 'STDIN' ) {
        $fh = *STDIN;
    }
    else {
        open $fh, "<", $file
            or die "fail to open file: $file\n";
    }

    my ( $header, $seq ) = ( "", "" );
    while (<$fh>) {
        s/\r?\n//g;
        s/^\s+|\s+$//g;
        next if $_ eq ''    # blank line
            or /^#/;        # annotation

        # first column as header, and second column as sequence,
        # ignore others
        ( $header, $seq ) = split /\t/, $_;

        $header =~ s/__tab__/\t/g;

        print ">$header\n$seq\n";
    }
}
